### ISSUE TITLE
Invalid `Origin` Header crashes Application

### ISSUE THREAD

**Issue by boesing** [zf-fr/zfr-cors#44]
We experience some Issues in our Application:

```
exception 'Zend\Http\Header\Exception\InvalidArgumentException' with message 'Invalid header value for Origin key: "Origin"' in ./vendor/zendframework/zend-http/src/Header/Origin.php:36
Stack trace:
#0 ./vendor/zendframework/zend-http/src/Headers.php(448): Zend\Http\Header\Origin::fromString('Origin: file:')
#1 ./vendor/zendframework/zend-http/src/Headers.php(287): Zend\Http\Headers->lazyLoadHeader(11)
#2 ./vendor/zfr/zfr-cors/src/ZfrCors/Service/CorsService.php(65): Zend\Http\Headers->get('Origin')
#3 ./vendor/zfr/zfr-cors/src/ZfrCors/Mvc/CorsRequestListener.php(83): ZfrCors\Service\CorsService->isCorsRequest(Object(Zend\Http\PhpEnvironment\Request))
#4 [internal function]: ZfrCors\Mvc\CorsRequestListener->onCorsPreflight(Object(Zend\Mvc\MvcEvent))
#5 ./vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 ./vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('route', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 ./vendor/zendframework/zend-mvc/src/Application.php(319): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 ./public/index.php(37): Zend\Mvc\Application->run()
#9 {main}
```

**Comment by amahrt** [comment]
'Origin: file:' doesn't look like a valid origin for me. What does your configuration look like?

**Comment by boesing** [comment]
Its not that we are triggering this behavior on our own. Some of the users obviously send this Header, therefore they can send whatever they want to.
However, I dont think the whole Application should crash just because a user is sending an invalid Header value.

**Comment by amahrt** [comment]
What else do you expect when this case occurs? We could implement a fallback value for the Origin header but that would cause unexpected behaviors, right?

**Comment by amahrt** [comment]
Maybe we should then return a 400 Bad request status code.

**Comment by boesing** [comment]
I've created a PR. Actually, the service just should treat invalid `Origin` values as non CORS requests.

**Comment by boesing** [comment]
@amahrt What do you think about the latest changes in #45?
